# Generated by Django 5.0.6 on 2024-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
