# Generated by Django 5.0.6 on 2024-07-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_categories_alter_product_category_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='url',
        ),
    ]
